import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import styles from './auth/layout.module.scss';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}> 
        <div className={styles.authLayout}>
          <video src="https://res.cloudinary.com/dsltlng97/video/upload/v1751466457/stadium-lights_vi9bhe.mp4" id="video" muted loop autoPlay className={styles.authBackground} />
 
            <main className={styles.authModal}>{children}</main> 
           
        </div>
      </body>
    </html>
  );
}
