import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import styles from './layout.module.scss';
import AlertCenter from '@/layout/alertCenter/AlertCenter.layout';
import { Suspense } from 'react';
import Loader from '@/components/loader/Loader.component';
import AuthPage from '@/layout/authPage/AuthPage.layout';
import Image from 'next/image';
import ReactQueryProvider from '@/providers/ReactQueryProvider';
import Footer from '@/layout/footer/Footer.layout';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className={styles.authLayout}>
          <video src="https://res.cloudinary.com/dsltlng97/video/upload/v1751466457/stadium-lights_vi9bhe.mp4" id="video" muted loop autoPlay className={styles.authBackground} />
          <AlertCenter />
          {/* <div className={styles.authBackground} /> */}
          <div className={styles.authOverlay}>
            <div className={styles.authContainer}>
              <Suspense fallback={<Loader />}>
                <AuthPage>
                  <Image src={`/images/fap icon.png`} alt="The Free Agent Portal Logo" priority width={160} height={160} />
                  <ReactQueryProvider>
                    <main className={styles.authModal}>{children}</main>
                  </ReactQueryProvider>
                  <Footer />
                </AuthPage>
              </Suspense>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
